/**
 * GENERATED by scripts/generate-borders.mjs, do not edit by hand.
 * Political border keyframes derived from aourednik/historical-basemaps
 * (GPL-3.0), world-scale approximations, simplified and clipped; see the
 * Methodology page. Per-year JSON lives in public/borders/ and is lazy-loaded.
 */

export interface BorderEntity {
  /** entity name as given by the source dataset */
  n: string;
  /** 1 = Muslim-ruled (display flag, curated), 0 = other power */
  m: 0 | 1;
  /** optional link to a timeline record id */
  r?: string;
  /** polygon rings, pre-projected [x, y][] */
  p: [number, number][][];
}
export interface BorderYear {
  y: number;
  s: BorderEntity[];
}

export const BORDER_KEYFRAMES: number[] = [
  -3000, -2000, -1500, -1000, -500, -200, -1, 100, 200, 300, 400, 500, 600, 700,
  800, 900, 1000, 1100, 1200, 1300, 1400, 1492, 1500, 1600, 1650, 1700, 1800,
  1880, 1900, 1914, 1920, 1938, 1945, 1960, 2010,
];

export function nearestBorderKeyframe(year: number): number {
  let best = BORDER_KEYFRAMES[0];
  for (const y of BORDER_KEYFRAMES)
    if (Math.abs(y - year) < Math.abs(best - year)) best = y;
  return best;
}

const cache = new Map<number, Promise<BorderYear>>();

/** Lazy-load a border keyframe from public/borders (cached). */
export function loadBorderYear(kf: number): Promise<BorderYear> {
  if (!cache.has(kf)) {
    const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
    cache.set(
      kf,
      fetch(`${base}/borders/y${kf}.json`).then((r) => {
        if (!r.ok) throw new Error(`borders y${kf}: HTTP ${r.status}`);
        return r.json() as Promise<BorderYear>;
      }),
    );
  }
  return cache.get(kf)!;
}
