/**
 * Collects the self-hosted font faces into one stylesheet under public/, so the
 * document's critical CSS does not carry them.
 *
 * The fonts are ~390 kB across five files. Discovered from the critical CSS they
 * compete for bandwidth with everything the first paint needs, which measured as
 * 1.7 s of extra wait on a throttled phone. Loaded after the first paint they
 * cost nothing: every face already declares font-display: swap, so text appears
 * immediately in the fallback and swaps when the face arrives.
 *
 * Run `npm run build:fonts` after changing a font dependency; the output is
 * committed.
 */
import { mkdirSync, readFileSync, writeFileSync, copyFileSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const SOURCES = [
  "@fontsource-variable/eb-garamond/index.css",
  "@fontsource-variable/inter/index.css",
  "@fontsource/amiri/400.css",
  "@fontsource/amiri/700.css",
];

const OUT_DIR = resolve("public/fonts");
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

let css = `/* GENERATED by scripts/build-fonts.mjs, do not edit by hand.
   Self-hosted faces, loaded after the first paint. See the script for why. */\n`;
let copied = 0;

for (const spec of SOURCES) {
  const file = resolve("node_modules", spec);
  const base = dirname(file);
  let text = readFileSync(file, "utf8");

  // keep woff2 only: every browser that can run this site supports it
  text = text.replace(/src:\s*([^;]+);/g, (_m, src) => {
    const woff2 = src
      .split(",")
      .map((s) => s.trim())
      .filter((s) => /\.woff2(['")]|$)/.test(s));
    return `src: ${woff2.join(", ")};`;
  });

  text = text.replace(/url\(([^)]+)\)/g, (_m, raw) => {
    const rel = raw.replace(/['"]/g, "").trim();
    const name = rel.split("/").pop();
    copyFileSync(join(base, rel), join(OUT_DIR, name));
    copied++;
    return `url('fonts/${name}')`;
  });

  css += `\n/* ${spec} */\n${text.trim()}\n`;
}

writeFileSync(resolve("public/fonts.css"), css);
console.log(`fonts: ${copied} files into public/fonts/, stylesheet at public/fonts.css`);
