/**
 * Generates src/data/geo/land-path.ts, a simplified Afro-Eurasian coastline
 * as an SVG path, projected with a plain equirectangular projection.
 *
 * Source: world-atlas (Natural Earth, public domain), land-110m.
 * Run: node scripts/generate-land.mjs (output is committed, so users don't need to)
 */
import { createRequire } from "module";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const require = createRequire(import.meta.url);
const topojson = require("topojson-client");
const land110 = require("world-atlas/land-110m.json");

// Map extent (must match MapPanel constants)
export const LON_MIN = -20;
export const LON_MAX = 115;
export const LAT_MIN = -12;
export const LAT_MAX = 62;
export const W = 1000;
export const H = 548;

const px = (lon) => ((lon - LON_MIN) / (LON_MAX - LON_MIN)) * W;
const py = (lat) => ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * H;

const land = topojson.feature(land110, land110.objects.land);

let d = "";
let rings = 0;
for (const poly of land.features[0].geometry.coordinates) {
  for (const ring of poly) {
    // keep rings that intersect our bbox (with margin)
    const inside = ring.some(
      ([lon, lat]) =>
        lon > LON_MIN - 15 &&
        lon < LON_MAX + 15 &&
        lat > LAT_MIN - 15 &&
        lat < LAT_MAX + 15,
    );
    if (!inside) continue;
    rings++;
    let first = true;
    for (const [lon, lat] of ring) {
      const x = px(lon).toFixed(1);
      const y = py(lat).toFixed(1);
      d += first ? `M${x},${y}` : `L${x},${y}`;
      first = false;
    }
    d += "Z";
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, "../src/data/geo/land-path.ts");
writeFileSync(
  out,
  `/**
 * GENERATED by scripts/generate-land.mjs, do not edit by hand.
 * Simplified land outline from Natural Earth (public domain) via world-atlas,
 * equirectangular projection over lon ${LON_MIN}…${LON_MAX}, lat ${LAT_MIN}…${LAT_MAX}.
 */
export const LAND_VIEWBOX = { w: ${W}, h: ${H} };
export const LON_MIN = ${LON_MIN};
export const LON_MAX = ${LON_MAX};
export const LAT_MIN = ${LAT_MIN};
export const LAT_MAX = ${LAT_MAX};
export function projectX(lon: number): number {
 return ((lon - LON_MIN) / (LON_MAX - LON_MIN)) * ${W};
}
export function projectY(lat: number): number {
 return ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * ${H};
}
export const LAND_PATH = ${JSON.stringify(d)};
`,
);
console.log(
  `Wrote ${out} (${rings} rings, ${(d.length / 1024).toFixed(0)} KB)`,
);
