/**
 * GENERATED by scripts/generate-borders.mjs, do not edit by hand.
 * Political border keyframes derived from aourednik/historical-basemaps
 * (GPL-3.0), world-scale approximations, simplified and clipped; see the
 * Methodology page. Coordinates are pre-projected to the atlas viewBox.
 */
import y600 from "./y600.json";
import y700 from "./y700.json";
import y800 from "./y800.json";
import y900 from "./y900.json";
import y1000 from "./y1000.json";
import y1100 from "./y1100.json";
import y1200 from "./y1200.json";
import y1300 from "./y1300.json";
import y1400 from "./y1400.json";
import y1492 from "./y1492.json";
import y1500 from "./y1500.json";
import y1600 from "./y1600.json";
import y1650 from "./y1650.json";
import y1700 from "./y1700.json";
import y1800 from "./y1800.json";
import y1880 from "./y1880.json";
import y1900 from "./y1900.json";
import y1914 from "./y1914.json";
import y1920 from "./y1920.json";
import y1938 from "./y1938.json";
import y1945 from "./y1945.json";
import y1960 from "./y1960.json";
import y2010 from "./y2010.json";

export interface BorderEntity {
  /** entity name as given by the source dataset */
  n: string;
  /** 1 = Muslim-ruled (display flag, curated), 0 = other power */
  m: 0 | 1;
  /** optional link to a timeline record id */
  r?: string;
  /** polygon rings, pre-projected [x, y][] */
  p: [number, number][][];
}
export interface BorderYear {
  y: number;
  s: BorderEntity[];
}

export const BORDER_YEARS: BorderYear[] = [
  y600 as unknown as BorderYear,
  y700 as unknown as BorderYear,
  y800 as unknown as BorderYear,
  y900 as unknown as BorderYear,
  y1000 as unknown as BorderYear,
  y1100 as unknown as BorderYear,
  y1200 as unknown as BorderYear,
  y1300 as unknown as BorderYear,
  y1400 as unknown as BorderYear,
  y1492 as unknown as BorderYear,
  y1500 as unknown as BorderYear,
  y1600 as unknown as BorderYear,
  y1650 as unknown as BorderYear,
  y1700 as unknown as BorderYear,
  y1800 as unknown as BorderYear,
  y1880 as unknown as BorderYear,
  y1900 as unknown as BorderYear,
  y1914 as unknown as BorderYear,
  y1920 as unknown as BorderYear,
  y1938 as unknown as BorderYear,
  y1945 as unknown as BorderYear,
  y1960 as unknown as BorderYear,
  y2010 as unknown as BorderYear,
];

export function nearestBorderYear(year: number): BorderYear {
  let best = BORDER_YEARS[0];
  for (const b of BORDER_YEARS)
    if (Math.abs(b.y - year) < Math.abs(best.y - year)) best = b;
  return best;
}
